### ISSUE TITLE
issue super admin

### ISSUE THREAD

**Issue by nandamaull244** [RhineAI/trident_ease#6]
![WhatsApp Image 2024-01-01 at 5 44 31 PM](https://github.com/RhineAI/trident_ease/assets/110996947/9c4c67f7-e667-4c14-88d3-bb178a402ba9)
akun super admin kita malah terkait dengan perusahaan user yang seharusnya jangan dan imbasnya level nya ikut tergantung perusahaan user

![WhatsApp Image 2024-01-01 at 5 45 28 PM](https://github.com/RhineAI/trident_ease/assets/110996947/b2895650-ea94-4395-ac62-8a6613eaa4fc)

id di db seed untuk super admin yang memengaruhi, let's fix this issues!

**Comment by RhineAI** [comment]
done bang
